name: Basic MLOps CI Workflow

on:
  push:
    branches:
      - main
    paths:
      - 'data/**'
      - 'train/**'
      - 'requirements.txt'
  pull_request:

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Training Script
        run: python train/train.py

      - name: Commit and Push Model
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add model/
          git diff --staged --quiet || git commit -m "Update trained model [skip ci]"
          git push
